spring.application.name=FoodApp
server.port=8090


# MYSQL CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/fooddb
spring.datasource.username=root
spring.datasource.password=Easin#@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update


secreteJwtString=food123456789app123456789food123456789app123456789
